
import Head from 'next/head'
import Hero from './sections/Hero'
import Social from './sections/Social'
import Value from './sections/Value'
import CTA from './sections/CTA'
import Navbar from '../components/Navbar'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-center items-center'>
        <Navbar />
        <Hero/>
        <Social/>
        <Value />
        <CTA />
      </main>
    </>
  )
}
